/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { WebApi2FeaturesAccountsTransaction } from '../models/web-api-2-features-accounts-transaction';
import { webApi2FeaturesAccountsTransactionsEndpoint } from '../fn/accounts/web-api-2-features-accounts-transactions-endpoint';
import { WebApi2FeaturesAccountsTransactionsEndpoint$Params } from '../fn/accounts/web-api-2-features-accounts-transactions-endpoint';

@Injectable({ providedIn: 'root' })
export class AccountsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `webApi2FeaturesAccountsTransactionsEndpoint()` */
  static readonly WebApi2FeaturesAccountsTransactionsEndpointPath = '/api/accounts/transactions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `webApi2FeaturesAccountsTransactionsEndpoint()` instead.
   *
   * This method doesn't expect any request body.
   */
  webApi2FeaturesAccountsTransactionsEndpoint$Response(params?: WebApi2FeaturesAccountsTransactionsEndpoint$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WebApi2FeaturesAccountsTransaction>>> {
    return webApi2FeaturesAccountsTransactionsEndpoint(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `webApi2FeaturesAccountsTransactionsEndpoint$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  webApi2FeaturesAccountsTransactionsEndpoint(params?: WebApi2FeaturesAccountsTransactionsEndpoint$Params, context?: HttpContext): Observable<Array<WebApi2FeaturesAccountsTransaction>> {
    return this.webApi2FeaturesAccountsTransactionsEndpoint$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<WebApi2FeaturesAccountsTransaction>>): Array<WebApi2FeaturesAccountsTransaction> => r.body)
    );
  }

}
