/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { webApi2FeaturesCategoriesAccountsEndpoint } from '../fn/categories/web-api-2-features-categories-accounts-endpoint';
import { WebApi2FeaturesCategoriesAccountsEndpoint$Params } from '../fn/categories/web-api-2-features-categories-accounts-endpoint';
import { WebApi2FeaturesCategoriesCategory } from '../models/web-api-2-features-categories-category';

@Injectable({ providedIn: 'root' })
export class CategoriesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `webApi2FeaturesCategoriesAccountsEndpoint()` */
  static readonly WebApi2FeaturesCategoriesAccountsEndpointPath = '/api/categories';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `webApi2FeaturesCategoriesAccountsEndpoint()` instead.
   *
   * This method doesn't expect any request body.
   */
  webApi2FeaturesCategoriesAccountsEndpoint$Response(params?: WebApi2FeaturesCategoriesAccountsEndpoint$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WebApi2FeaturesCategoriesCategory>>> {
    return webApi2FeaturesCategoriesAccountsEndpoint(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `webApi2FeaturesCategoriesAccountsEndpoint$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  webApi2FeaturesCategoriesAccountsEndpoint(params?: WebApi2FeaturesCategoriesAccountsEndpoint$Params, context?: HttpContext): Observable<Array<WebApi2FeaturesCategoriesCategory>> {
    return this.webApi2FeaturesCategoriesAccountsEndpoint$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<WebApi2FeaturesCategoriesCategory>>): Array<WebApi2FeaturesCategoriesCategory> => r.body)
    );
  }

}
