/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WebApi2FeaturesDashboardCashflowCashFlowItem {
  amount: number;
  from: string;
  to: string;
}
