/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WebApi2FeaturesAccountsTransaction {
  accountId: number;
  amount: number;
  date: string;
  id?: number | null;
  purposeOfUse?: string | null;
  transactionCategoryId?: number | null;
}
