/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WebApi2FeaturesDashboardIncomeVsExpenseDashboardIncomeVsExpense {
  difference: number;
  expense: number;
  income: number;
}
