/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InfrastructureTransactionCategoryType } from '../models/infrastructure-transaction-category-type';
export interface WebApi2FeaturesCategoriesCategory {
  id?: number | null;
  name?: string | null;
  parentId?: number | null;
  type: InfrastructureTransactionCategoryType;
}
