/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WebApi2FeaturesDashboardIncomeVsExpenseDashboardIncomeVsExpense } from '../../models/web-api-2-features-dashboard-income-vs-expense-dashboard-income-vs-expense';

export interface WebApi2FeaturesDashboardIncomeVsExpenseIncomeVsExpenseEndpoint$Params {
  from?: string | null;
}

export function webApi2FeaturesDashboardIncomeVsExpenseIncomeVsExpenseEndpoint(http: HttpClient, rootUrl: string, params?: WebApi2FeaturesDashboardIncomeVsExpenseIncomeVsExpenseEndpoint$Params, context?: HttpContext): Observable<StrictHttpResponse<WebApi2FeaturesDashboardIncomeVsExpenseDashboardIncomeVsExpense>> {
  const rb = new RequestBuilder(rootUrl, webApi2FeaturesDashboardIncomeVsExpenseIncomeVsExpenseEndpoint.PATH, 'get');
  if (params) {
    rb.query('from', params.from, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WebApi2FeaturesDashboardIncomeVsExpenseDashboardIncomeVsExpense>;
    })
  );
}

webApi2FeaturesDashboardIncomeVsExpenseIncomeVsExpenseEndpoint.PATH = '/api/dashboard/income-vs-expense';
