/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WebApi2FeaturesDashboardHistoryDashboardHistoryItem } from '../../models/web-api-2-features-dashboard-history-dashboard-history-item';

export interface WebApi2FeaturesDashboardHistoryTotalNetWorthHistoryTotalNetWorthEndpoint$Params {
  from?: string | null;
}

export function webApi2FeaturesDashboardHistoryTotalNetWorthHistoryTotalNetWorthEndpoint(http: HttpClient, rootUrl: string, params?: WebApi2FeaturesDashboardHistoryTotalNetWorthHistoryTotalNetWorthEndpoint$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WebApi2FeaturesDashboardHistoryDashboardHistoryItem>>> {
  const rb = new RequestBuilder(rootUrl, webApi2FeaturesDashboardHistoryTotalNetWorthHistoryTotalNetWorthEndpoint.PATH, 'get');
  if (params) {
    rb.query('from', params.from, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WebApi2FeaturesDashboardHistoryDashboardHistoryItem>>;
    })
  );
}

webApi2FeaturesDashboardHistoryTotalNetWorthHistoryTotalNetWorthEndpoint.PATH = '/api/dashboard/history/total-net-worth';
