/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WebApi2FeaturesDashboardCashflowCashFlowItem } from '../../models/web-api-2-features-dashboard-cashflow-cash-flow-item';

export interface WebApi2FeaturesDashboardCashflowCashflowEndpoint$Params {
  from?: string | null;
}

export function webApi2FeaturesDashboardCashflowCashflowEndpoint(http: HttpClient, rootUrl: string, params?: WebApi2FeaturesDashboardCashflowCashflowEndpoint$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WebApi2FeaturesDashboardCashflowCashFlowItem>>> {
  const rb = new RequestBuilder(rootUrl, webApi2FeaturesDashboardCashflowCashflowEndpoint.PATH, 'get');
  if (params) {
    rb.query('from', params.from, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WebApi2FeaturesDashboardCashflowCashFlowItem>>;
    })
  );
}

webApi2FeaturesDashboardCashflowCashflowEndpoint.PATH = '/api/dashboard/cash-flow';
