/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WebApi2FeaturesDashboardKpisDashboardKpi } from '../../models/web-api-2-features-dashboard-kpis-dashboard-kpi';

export interface WebApi2FeaturesDashboardKpisTotalNetWorthEndpoint$Params {
  from?: string | null;
}

export function webApi2FeaturesDashboardKpisTotalNetWorthEndpoint(http: HttpClient, rootUrl: string, params?: WebApi2FeaturesDashboardKpisTotalNetWorthEndpoint$Params, context?: HttpContext): Observable<StrictHttpResponse<WebApi2FeaturesDashboardKpisDashboardKpi>> {
  const rb = new RequestBuilder(rootUrl, webApi2FeaturesDashboardKpisTotalNetWorthEndpoint.PATH, 'get');
  if (params) {
    rb.query('from', params.from, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WebApi2FeaturesDashboardKpisDashboardKpi>;
    })
  );
}

webApi2FeaturesDashboardKpisTotalNetWorthEndpoint.PATH = '/api/dashboard/kpis/total-net-worth';
