/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { WebApi2FeaturesDashboardHistoryDashboardHistoryItem } from './models/web-api-2-features-dashboard-history-dashboard-history-item';
export type { WebApi2FeaturesDashboardIncomeVsExpenseDashboardIncomeVsExpense } from './models/web-api-2-features-dashboard-income-vs-expense-dashboard-income-vs-expense';
export type { WebApi2FeaturesDashboardKpisDashboardKpi } from './models/web-api-2-features-dashboard-kpis-dashboard-kpi';
