/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { DashboardService } from './services/dashboard.service';
export { ApiService } from './services/api.service';
