/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WebApi2FeaturesAccountsAccount } from '../../models/web-api-2-features-accounts-account';

export interface WebApi2FeaturesAccountsAccountsEndpoint$Params {
}

export function webApi2FeaturesAccountsAccountsEndpoint(http: HttpClient, rootUrl: string, params?: WebApi2FeaturesAccountsAccountsEndpoint$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WebApi2FeaturesAccountsAccount>>> {
  const rb = new RequestBuilder(rootUrl, webApi2FeaturesAccountsAccountsEndpoint.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WebApi2FeaturesAccountsAccount>>;
    })
  );
}

webApi2FeaturesAccountsAccountsEndpoint.PATH = '/api/accounts';
